package com.example.data

import android.util.Log
import com.example.BuildConfig
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

object GeminiService {
    private const val TAG = "GeminiService"
    private const val MODEL_NAME = "gemini-3.5-flash"
    private const val BASE_URL = "https://generativelanguage.googleapis.com/v1beta/models/$MODEL_NAME:generateContent"

    private val client = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .writeTimeout(30, TimeUnit.SECONDS)
        .build()

    suspend fun generateReply(prompt: String, customerContext: String = ""): String = withContext(Dispatchers.IO) {
        val apiKey = try {
            BuildConfig.GEMINI_API_KEY
        } catch (e: Exception) {
            ""
        }

        if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext "Error: API Key is not set in AI Studio Secrets panel. Please check your settings."
        }

        val systemInstructionText = """
            You are an expert customer service representative for a small business. 
            Draft a polite, highly professional, helpful, and concise response to the customer. 
            Write the response in Bengali (using polite language like 'আপনি', 'ধন্যবাদ') or English, matching the user's input language. 
            Keep it actionable and short enough to be sent as a chat message. 
            Do NOT include placeholders like '[Your Name]', leave them blank or make them generic.
        """.trimIndent()

        val fullPromptText = if (customerContext.isNotEmpty()) {
            "Customer Query/Issue: $customerContext\n\nDraft a quick reply to: $prompt"
        } else {
            prompt
        }

        try {
            // Build direct JSON payload
            val jsonPayload = JSONObject().apply {
                val contentsArray = JSONArray().apply {
                    val contentObj = JSONObject().apply {
                        val partsArray = JSONArray().apply {
                            val partObj = JSONObject().apply {
                                put("text", fullPromptText)
                            }
                            put(partObj)
                        }
                        put("parts", partsArray)
                    }
                    put(contentObj)
                }
                put("contents", contentsArray)

                val systemInstructionObj = JSONObject().apply {
                    val partsArray = JSONArray().apply {
                        val partObj = JSONObject().apply {
                            put("text", systemInstructionText)
                        }
                        put(partObj)
                    }
                    put("parts", partsArray)
                }
                put("systemInstruction", systemInstructionObj)
            }

            val requestBody = jsonPayload.toString().toRequestBody("application/json".toMediaType())
            val request = Request.Builder()
                .url("$BASE_URL?key=$apiKey")
                .post(requestBody)
                .build()

            client.newCall(request).execute().use { response ->
                val bodyString = response.body?.string()
                if (!response.isSuccessful) {
                    Log.e(TAG, "Request failed: ${response.code}, Body: $bodyString")
                    return@withContext "Error code ${response.code}: Failed to generate reply."
                }

                if (bodyString != null) {
                    val responseJson = JSONObject(bodyString)
                    val candidates = responseJson.optJSONArray("candidates")
                    if (candidates != null && candidates.length() > 0) {
                        val firstCandidate = candidates.getJSONObject(0)
                        val content = firstCandidate.optJSONObject("content")
                        val parts = content?.optJSONArray("parts")
                        if (parts != null && parts.length() > 0) {
                            val firstPart = parts.getJSONObject(0)
                            val text = firstPart.optString("text")
                            if (!text.isNullOrEmpty()) {
                                return@withContext text.trim()
                            }
                        }
                    }
                }
                return@withContext "No response text was generated by Gemini."
            }
        } catch (e: Exception) {
            Log.e(TAG, "Exception during generation", e)
            return@withContext "Error: ${e.message}"
        }
    }
}
